blank_issues_enabled: false
contact_links:
  - name: Documentation 📚
    url: https://github.com/Farfetch/kafkaflow-retry-extensions/wiki
    about: Check out the official docs for answers to common questions